-- =======================================================
-- Rewply AI Database Seed Data (50 Reviews for BurgerHub Delivery)
-- =======================================================

-- 1. CLEAN EXISTING DATA (Optional)
TRUNCATE TABLE public.reviews CASCADE;
TRUNCATE TABLE public.issues CASCADE;
TRUNCATE TABLE public.business_metrics CASCADE;

-- 2. SEED BUSINESS METRICS
INSERT INTO public.business_metrics (id, reputation_score, total_reviews, sentiment_breakdown, calculated_at)
VALUES (
  'd1a10001-0000-4000-8000-000000000001',
  72,
  50,
  '{"positive": 12, "neutral": 5, "negative": 33}'::jsonb,
  '2026-08-28T22:00:00Z'
);

-- 3. SEED ISSUES
INSERT INTO public.issues (id, issue_type, category, mention_count, trend_direction, severity_score, created_at)
VALUES
('e1a10001-0000-4000-8000-000000000001', 'Delivery Delays (>60 mins)', 'Delivery', 15, 'up', 9, '2026-08-28T00:00:00Z'),
('e1a10002-0000-4000-8000-000000000002', 'Undercooked / Raw Meat', 'Food Quality', 10, 'down', 8, '2026-08-28T00:00:00Z'),
('e1a10003-0000-4000-8000-000000000003', 'Checkout & Promo Code Errors', 'Billing', 8, 'stable', 7, '2026-08-28T00:00:00Z'),
('e1a10004-0000-4000-8000-000000000004', 'App Crash & OTP Lag', 'App/Technical', 5, 'down', 6, '2026-08-28T00:00:00Z'),
('e1a10005-0000-4000-8000-000000000005', 'Missing Drinks & Sides', 'Delivery', 7, 'stable', 7, '2026-08-28T00:00:00Z');

-- 4. SEED 50 REVIEWS
INSERT INTO public.reviews (id, platform, customer_name, review_text, rating, created_at, analysis, ai_response, response_status)
VALUES
-- --- 15 DELIVERY COMPLAINTS ---
('f1a10001-0000-4000-8000-000000000001', 'google', 'Marcus Vance', 'Ordered the Double Truffle Smash burger at 7:15 PM and it arrived stone cold at 8:50 PM. Driver claimed traffic was bad, but tracking showed him stationary 2 miles away for 40 minutes. Ruined dinner night.', 1, '2026-08-28T19:55:00Z', '{"sentiment": "negative", "emotion": "frustrated", "issue": "Extreme delivery delay & cold food", "urgency": "high", "priority": "P1"}'::jsonb, 'Hi Marcus, we are deeply sorry for the 90+ minute delay and for your meal arriving cold. That is far below our delivery standard. We have flagged this courier route with our logistics team and issued an immediate full refund plus a $15 credit to your BurgerHub account.', 'approved'),
('f1a10002-0000-4000-8000-000000000002', 'yelp', 'Sophia Chen', 'The delivery driver dropped the bag right onto my porch steps upside down. The drinks burst open and soaked all the burger buns into mush. Tried calling support but no answer.', 1, '2026-08-27T18:20:00Z', '{"sentiment": "negative", "emotion": "angry", "issue": "Mishandled package & spilled drinks", "urgency": "high", "priority": "P1"}'::jsonb, 'Hello Sophia, seeing your order damaged like that is unacceptable. We sincerely apologize for the careless handling by the driver and the unresponsive support. We are reprocessing a full replacement order at no charge and refunding your delivery fee right away.', 'sent'),
('f1a10003-0000-4000-8000-000000000003', 'trustpilot', 'David Reynolds', 'Driver left the food at the wrong building entirely (Building B instead of Building D) and didn’t even ring the buzzer or take a clear drop-off photo. By the time I hunted it down, the fries were soggy.', 2, '2026-08-26T20:10:00Z', '{"sentiment": "negative", "emotion": "annoyed", "issue": "Incorrect delivery address drop-off", "urgency": "medium", "priority": "P2"}'::jsonb, 'Hi David, we apologize for the misplacement of your order and the lack of proper delivery confirmation. We''ve reinforced apartment delivery protocol with our courier partner and credited $10 to your account for the inconvenience.', 'pending'),
('f1a10004-0000-4000-8000-000000000004', 'google', 'Elena Rostova', 'Estimated delivery was 25-35 mins. It took over 75 mins on a Tuesday afternoon. Burger was lukewarm and cheese had hardened back up.', 2, '2026-08-25T14:40:00Z', '{"sentiment": "negative", "emotion": "disappointed", "issue": "Inaccurate ETA and delayed delivery", "urgency": "medium", "priority": "P2"}'::jsonb, 'Dear Elena, thank you for alerting us. A 75-minute wait on a weekday afternoon is unacceptable. We are recalibrating our dispatch routing algorithms and have sent a 50% discount voucher to your email.', 'approved'),
('f1a10005-0000-4000-8000-000000000005', 'yelp', 'Brian K. Miller', 'Driver took multiple stops in the opposite direction before heading to my place. BurgerHub needs dedicated couriers or better thermal bags.', 2, '2026-08-24T21:15:00Z', '{"sentiment": "negative", "emotion": "frustrated", "issue": "Inefficient multi-stop batching", "urgency": "medium", "priority": "P2"}'::jsonb, 'Hello Brian, we hear you loud and clear. Stacked orders should never compromise temperature. We are upgrading all partner fleets to insulated heat-retaining thermal pods and reviewing courier route stacking.', 'sent'),
('f1a10006-0000-4000-8000-000000000006', 'google', 'Chloe Bennett', 'My order was marked as "Delivered" on the app but nothing was outside my door or lobby. Had to wait 30 minutes for support to figure out it was left on the street sidewalk!', 1, '2026-08-24T12:30:00Z', '{"sentiment": "negative", "emotion": "furious", "issue": "Premature delivery mark & sidewalk dump", "urgency": "high", "priority": "P1"}'::jsonb, 'Hi Chloe, this is appalling behavior from the assigned driver. We have blocked this courier from delivering BurgerHub orders and refunded your entire order instantly along with a direct apology credit.', 'approved'),
('f1a10007-0000-4000-8000-000000000007', 'trustpilot', 'Timothy Wright', 'Courier refused to bring the order to the 3rd floor apartment despite specific instructions and elevator access. Forced me to come down in the rain.', 2, '2026-08-23T19:05:00Z', '{"sentiment": "negative", "emotion": "annoyed", "issue": "Courier refusal to complete doorstep delivery", "urgency": "medium", "priority": "P2"}'::jsonb, 'Hi Timothy, our door-to-door policy requires drivers to deliver straight to your apartment door when access is available. We apologize for the hassle and have reminded the local courier team of our service rules.', 'pending'),
('f1a10008-0000-4000-8000-000000000008', 'google', 'Jessica Gomez', 'Food arrived an hour late, and the seal sticker on the BurgerHub bag was torn open. Did not feel safe eating the food.', 1, '2026-08-22T20:45:00Z', '{"sentiment": "negative", "emotion": "distressed", "issue": "Tampered safety seal & excessive delay", "urgency": "high", "priority": "P1"}'::jsonb, 'Dear Jessica, food safety and hygiene are our number one priority. A broken tamper seal is completely unacceptable. We have initiated a full refund and launched an immediate inquiry with the delivery partner.', 'sent'),
('f1a10009-0000-4000-8000-000000000009', 'yelp', 'Anthony Foster', 'Ordered lunch for an office meeting at 11:30 AM for 12:15 PM delivery. Arrived at 1:10 PM after everyone had already dispersed. Terrible reliability.', 1, '2026-08-21T13:15:00Z', '{"sentiment": "negative", "emotion": "embarrassed", "issue": "Late corporate/scheduled delivery", "urgency": "high", "priority": "P1"}'::jsonb, 'Hi Anthony, we understand how crucial timing is for corporate lunches and we deeply regret letting your team down. A full refund has been processed, and our corporate catering coordinator will contact you directly.', 'approved'),
('f1a10010-0000-4000-8000-000000000010', 'google', 'Samantha Lee', 'Driver forgot the 2 chocolate milkshakes and 2 large fries in his car and drove off. When I messaged him, he said contact support. Support took 2 days to reply.', 1, '2026-08-20T17:40:00Z', '{"sentiment": "negative", "emotion": "angry", "issue": "Missing items & slow customer support", "urgency": "high", "priority": "P1"}'::jsonb, 'Hi Samantha, we are truly sorry for the missing shakes and fries, as well as the delayed support response. We have refunded the missing items and credited your account with a complimentary combo voucher.', 'pending'),
('f1a10011-0000-4000-8000-000000000011', 'trustpilot', 'Oliver Hudson', 'The courier called me 4 times unable to find a simple street corner. Food was freezing by the time he finally handed it over.', 2, '2026-08-19T21:00:00Z', '{"sentiment": "negative", "emotion": "impatient", "issue": "Courier navigation difficulty & cold food", "urgency": "medium", "priority": "P2"}'::jsonb, 'Hello Oliver, thank you for your feedback. We are updating our in-app navigation integration to provide couriers with precise pin-drop GPS coordinates to prevent such delays in the future.', 'approved'),
('f1a10012-0000-4000-8000-000000000012', 'google', 'Rachel Sterling', 'Driver placed the bag right against an outward-swinging screen door. When I opened the door, it knocked over the drinks and smashed the burger.', 2, '2026-08-18T19:30:00Z', '{"sentiment": "negative", "emotion": "frustrated", "issue": "Poor drop-off placement blocking screen door", "urgency": "medium", "priority": "P2"}'::jsonb, 'Hi Rachel, placing deliveries right against outward-opening screen doors is a known driver error we train against. We are sending an instant credit for your meal and reinforcing door-clearance guidelines.', 'sent'),
('f1a10013-0000-4000-8000-000000000013', 'yelp', 'Daniel Peterson', 'Waited 50 minutes for a simple cheese burger combo only 1.2 miles away. Burger was sweaty in the plastic container and fries were limp.', 2, '2026-08-17T18:50:00Z', '{"sentiment": "negative", "emotion": "disappointed", "issue": "Slow short-distance delivery & soggy packaging", "urgency": "medium", "priority": "P2"}'::jsonb, 'Hi Daniel, 50 minutes for a 1.2 mile delivery is too slow. We are switching to ventilated craft packaging to keep fries crisp and reviewing kitchen-to-dispatch handoff times.', 'pending'),
('f1a10014-0000-4000-8000-000000000014', 'google', 'Hannah Brooks', 'Delivery was marked complete at 8 PM, but driver only showed up at 8:25 PM. He smelled strongly of cigarette smoke and the food bag absorbed the smell.', 1, '2026-08-16T20:30:00Z', '{"sentiment": "negative", "emotion": "disgusted", "issue": "Smoke odor on food package & false delivery status", "urgency": "high", "priority": "P1"}'::jsonb, 'Dear Hannah, this is completely unacceptable and breaches our partner code of conduct. We have taken immediate disciplinary action with the driver partner and issued a 100% refund for your order.', 'approved'),
('f1a10015-0000-4000-8000-000000000015', 'trustpilot', 'Kevin Zhao', 'BurgerHub delivery driver was extremely rude when asking for delivery gate code, shouting over the phone. Food was cold too.', 1, '2026-08-15T19:15:00Z', '{"sentiment": "negative", "emotion": "angry", "issue": "Courier unprofessionalism & cold food", "urgency": "high", "priority": "P1"}'::jsonb, 'Hello Kevin, we have zero tolerance for unprofessional conduct from our delivery partners. We have escalated this incident to fleet management and issued a complete refund plus compensation credit.', 'sent'),

-- --- 10 FOOD QUALITY ISSUES ---
('f1a20001-0000-4000-8000-000000000016', 'yelp', 'Austin Matthews', 'Ordered the Wagyu Smash Patty medium-well, but both patties were almost raw and pink in the middle. Couldn’t eat it. Really disappointed given the $22 price tag.', 1, '2026-08-28T20:00:00Z', '{"sentiment": "negative", "emotion": "concerned", "issue": "Undercooked raw beef patties", "urgency": "high", "priority": "P1"}'::jsonb, 'Hi Austin, thank you for bringing this to our attention. Serving undercooked patties is a serious kitchen quality lapse. Our head chef has reviewed grill temperature timers with line cooks. A full refund has been credited.', 'approved'),
('f1a20002-0000-4000-8000-000000000017', 'google', 'Megan Foxx', 'The brioche buns were completely stale and crumbly, like they were 4 days old. The bacon on the BBQ burger was burnt to a crisp black charcoal.', 2, '2026-08-27T13:45:00Z', '{"sentiment": "negative", "emotion": "disappointed", "issue": "Stale bakery bun & burnt bacon", "urgency": "medium", "priority": "P2"}'::jsonb, 'Hi Megan, we hold our bakery fresh deliveries to strict daily standards and burnt bacon should never leave the kitchen. We have re-audited our morning bread prep and sent you a replacement meal code.', 'pending'),
('f1a20003-0000-4000-8000-000000000018', 'google', 'Trevor Vance', 'Paid extra $3.50 for signature truffle aioli and caramelized onions. Neither was on the burger! Just dry plain meat and lettuce.', 2, '2026-08-26T19:20:00Z', '{"sentiment": "negative", "emotion": "frustrated", "issue": "Missing premium paid toppings & dry burger", "urgency": "medium", "priority": "P2"}'::jsonb, 'Hi Trevor, we apologize for missing the premium add-ons you paid for. We’ve credited back the add-on charge along with an extra discount for your next order to make it right.', 'approved'),
('f1a20004-0000-4000-8000-000000000019', 'trustpilot', 'Rebecca Dunn', 'The Truffle Parmesan Fries were completely drenched in old cooking oil and so salty they were inedible. Had to throw the entire box away.', 1, '2026-08-25T18:10:00Z', '{"sentiment": "negative", "emotion": "disgusted", "issue": "Over-salted & greasy old fryer oil", "urgency": "medium", "priority": "P2"}'::jsonb, 'Hello Rebecca, thank you for the honest review. We have performed a complete fryer oil flush and seasoning check at our central prep kitchen. We have refunded your side order in full.', 'sent'),
('f1a20005-0000-4000-8000-000000000020', 'yelp', 'Carlos Mendez', 'Ordered the Crispy Chicken Burger and the chicken breast was fibrous and rubbery. Tasted like it was microwaved rather than freshly fried.', 2, '2026-08-23T20:30:00Z', '{"sentiment": "negative", "emotion": "disappointed", "issue": "Rubbery texture / quality in chicken patty", "urgency": "medium", "priority": "P2"}'::jsonb, 'Hi Carlos, all our chicken is fresh-battered and fried to order, never microwaved. We are inspecting this batch with our poultry supplier. We’d love the chance to treat you to a better experience on us.', 'approved'),
('f1a20006-0000-4000-8000-000000000021', 'google', 'Danielle Moore', 'Found a small piece of hard plastic packaging inside the melted cheddar cheese. Very dangerous! Please check your kitchen prep stations.', 1, '2026-08-22T19:00:00Z', '{"sentiment": "negative", "emotion": "alarmed", "issue": "Foreign object in food (plastic piece)", "urgency": "high", "priority": "P1"}'::jsonb, 'Dear Danielle, this is an urgent health and safety concern. We have pulled that batch of cheese slices immediately and instituted mandatory prep inspection. Our QA manager will reach out directly.', 'approved'),
('f1a20007-0000-4000-8000-000000000022', 'yelp', 'Logan Wright', 'Burger patty was paper thin, completely overcooked and dry as cardboard. Used to love BurgerHub, but quality has plummeted recently.', 2, '2026-08-20T21:20:00Z', '{"sentiment": "negative", "emotion": "disillusioned", "issue": "Patty thickness & declining food consistency", "urgency": "medium", "priority": "P2"}'::jsonb, 'Hi Logan, we appreciate your loyalty and hate to hear we missed the mark. We are reviewing portioning and smash press calibrations with our kitchen team to restore the quality you expect.', 'pending'),
('f1a20008-0000-4000-8000-000000000023', 'trustpilot', 'Brooke Taylor', 'Ordered gluten-free bun due to gluten intolerance, but received regular wheat bun. Luckily noticed before taking a big bite. Careless kitchen error.', 1, '2026-08-18T18:40:00Z', '{"sentiment": "negative", "emotion": "angry", "issue": "Allergen / dietary modification failure", "urgency": "high", "priority": "P1"}'::jsonb, 'Dear Brooke, dietary modifications and allergens must always be handled with extreme care. We sincerely apologize for this critical mistake. We have retrained the assembly line on allergy tickets.', 'sent'),
('f1a20009-0000-4000-8000-000000000024', 'google', 'Jordan Hayes', 'The milkshakes were 80% liquid and melted like sweet warm milk. No ice cream texture left.', 2, '2026-08-16T15:20:00Z', '{"sentiment": "negative", "emotion": "disappointed", "issue": "Melted beverage / lack of insulation", "urgency": "low", "priority": "P3"}'::jsonb, 'Hi Jordan, during summer heat, shakes need special cold-pack courier inserts. We are rolling out insulated freeze pouches for all beverage orders. Refund issued for your shakes.', 'approved'),
('f1a20010-0000-4000-8000-000000000025', 'yelp', 'Vanessa Diaz', 'Sauce overload ruined what could have been a decent burger. The bun disintegrated within 2 minutes of opening the wrapper.', 2, '2026-08-14T20:15:00Z', '{"sentiment": "negative", "emotion": "annoyed", "issue": "Excessive sauce causing soggy disintegration", "urgency": "low", "priority": "P3"}'::jsonb, 'Hi Vanessa, thanks for pointing this out. We are standardizing our sauce dispenser portions to ensure burgers stay intact during transit without soggy buns.', 'pending'),

-- --- 8 BILLING PROBLEMS ---
('f1a30001-0000-4000-8000-000000000026', 'trustpilot', 'Gregory Scott', 'Applied a 25% discount promo code at checkout (SUMMERBURGER). The app showed the discounted total, but my credit card statement shows the full $48.50 charged!', 1, '2026-08-28T16:00:00Z', '{"sentiment": "negative", "emotion": "frustrated", "issue": "Promo code discount not applied to final card charge", "urgency": "high", "priority": "P1"}'::jsonb, 'Hi Gregory, we apologize for the billing discrepancy. We investigated the transaction, refunded the 25% difference ($12.12) to your card, and resolved the checkout gateway sync issue.', 'approved'),
('f1a30002-0000-4000-8000-000000000027', 'google', 'Patricia White', 'Cancelled an order within 30 seconds because I selected the wrong delivery address. Was told instant refund would process, but 10 days later still no money in my bank.', 1, '2026-08-27T11:20:00Z', '{"sentiment": "negative", "emotion": "angry", "issue": "Delayed cancellation refund processing", "urgency": "high", "priority": "P1"}'::jsonb, 'Hello Patricia, we deeply apologize for the refund delay. We have manually cleared the bank authorization release and credited your bank account, plus added $10 in BurgerHub perks.', 'approved'),
('f1a30003-0000-4000-8000-000000000028', 'yelp', 'Nathaniel Drake', 'Hidden $4.99 "Service Optimization Fee" added on top of delivery fee and taxes at the very last step. Very deceptive pricing.', 2, '2026-08-25T19:45:00Z', '{"sentiment": "negative", "emotion": "irritated", "issue": "Hidden fees & pricing transparency", "urgency": "medium", "priority": "P2"}'::jsonb, 'Hi Nathaniel, we appreciate your transparent feedback. We are updating our checkout breakdown so all service and logistics fees are clearly displayed upfront before cart review.', 'pending'),
('f1a30004-0000-4000-8000-000000000029', 'trustpilot', 'Fiona Gallagher', 'Charged twice on my Visa card for the same single order #BH-8921. Bank confirmed two separate identical authorizations.', 1, '2026-08-24T17:30:00Z', '{"sentiment": "negative", "emotion": "furious", "issue": "Duplicate credit card transaction charge", "urgency": "high", "priority": "P1"}'::jsonb, 'Hi Fiona, double charges are unacceptable. We immediately voided the duplicate authorization on order #BH-8921. The funds will reflect back in your account within 24–48 hours.', 'sent'),
('f1a30005-0000-4000-8000-000000000030', 'google', 'Warren Buffet Jr', 'Default tip calculation defaulted to 30% without explicit confirmation. Sneaky UI design.', 2, '2026-08-22T21:10:00Z', '{"sentiment": "negative", "emotion": "annoyed", "issue": "Aggressive default tip UI setting", "urgency": "low", "priority": "P3"}'::jsonb, 'Hello Warren, thank you for calling this out. In our latest app update (v2.4), we have reset default tip options to balanced tiers (15%, 18%, 20%) with a prominent custom tip selector.', 'approved'),
('f1a30006-0000-4000-8000-000000000031', 'trustpilot', 'Chloe Simmons', 'Purchased a $50 BurgerHub e-gift card for my brother’s birthday. The card balance showed $0 upon activation. Support took a week to resolve.', 2, '2026-08-19T14:15:00Z', '{"sentiment": "negative", "emotion": "frustrated", "issue": "Gift card balance activation glitch & slow support", "urgency": "medium", "priority": "P2"}'::jsonb, 'Hi Chloe, we apologize for the gift card activation glitch that impacted your brother''s gift. We fixed the voucher balance and loaded a complimentary $15 bonus balance to his account.', 'sent'),
('f1a30007-0000-4000-8000-000000000032', 'yelp', 'Justin Bieberly', 'Subscription loyalty program "BurgerPass" renewed and charged my card after I explicitly cancelled it 2 weeks prior in settings.', 1, '2026-08-17T12:00:00Z', '{"sentiment": "negative", "emotion": "angry", "issue": "Unwanted subscription renewal charge after cancellation", "urgency": "high", "priority": "P1"}'::jsonb, 'Hi Justin, we are very sorry for the billing sync error on your BurgerPass membership. We have processed a full refund for the renewal charge and confirmed cancellation in our system.', 'approved'),
('f1a30008-0000-4000-8000-000000000033', 'google', 'Ashley Parker', 'Receipt in the bag showed $32.00, but app charged me $39.50. Where did the extra $7.50 go? No itemized explanation.', 2, '2026-08-15T18:40:00Z', '{"sentiment": "negative", "emotion": "suspicious", "issue": "Receipt vs App checkout price discrepancy", "urgency": "medium", "priority": "P2"}'::jsonb, 'Hi Ashley, the printed ticket was an in-store base ticket before delivery dispatch fees. However, our digital receipts should always make this crystal clear. We have credited $8 to your wallet.', 'pending'),

-- --- 12 POSITIVE REVIEWS ---
('f1a40001-0000-4000-8000-000000000034', 'google', 'Liam Neeson-Smith', 'Hands down the best smash burger delivery in the city! Delivered in 22 minutes, piping hot, and the truffle aioli dip is to die for. 10/10.', 5, '2026-08-28T21:10:00Z', '{"sentiment": "positive", "emotion": "delighted", "issue": "None / Praise", "urgency": "low", "priority": "P3"}'::jsonb, 'Thank you so much Liam! We take immense pride in getting our smash burgers to you piping hot in record time. We can''t wait to deliver your next craving!', 'sent'),
('f1a40002-0000-4000-8000-000000000035', 'google', 'Emma Watson-Jones', 'BurgerHub Delivery saved our family game night. Ordered 6 custom combos, every single customization was 100% accurate, and food was fresh!', 5, '2026-08-27T20:30:00Z', '{"sentiment": "positive", "emotion": "grateful", "issue": "None / Praise", "urgency": "low", "priority": "P3"}'::jsonb, 'Hi Emma, nothing makes us happier than fueling family game nights with precision and fresh flavors! Thanks for choosing BurgerHub Delivery!', 'approved'),
('f1a40003-0000-4000-8000-000000000036', 'yelp', 'Zachary Taylor', 'The Smokey BBQ Bacon Burger had the crispiest bacon and the meat had that perfect caramelized crust. Driver was super polite too.', 5, '2026-08-26T18:00:00Z', '{"sentiment": "positive", "emotion": "enthusiastic", "issue": "None / Praise", "urgency": "low", "priority": "P3"}'::jsonb, 'Thanks Zachary! That caramelized smash crust is our signature craft. Thrilled our driver provided great service too. See you again soon!', 'sent'),
('f1a40004-0000-4000-8000-000000000037', 'google', 'Olivia Martinez', 'Crispy Cajun Fries were still actually crispy upon arrival! That ventilated box packaging they use really makes a huge difference.', 5, '2026-08-25T13:10:00Z', '{"sentiment": "positive", "emotion": "satisfied", "issue": "None / Praise", "urgency": "low", "priority": "P3"}'::jsonb, 'Hi Olivia, we spent months engineering our ventilated fry boxes to ensure crispy perfection on delivery. So glad you noticed the difference!', 'approved'),
('f1a40005-0000-4000-8000-000000000038', 'trustpilot', 'Lucas Graham', 'Incredible customer support. There was a slight 10 min delay due to thunderstorm, and they preemptively sent an apology text and $5 voucher before I even noticed.', 5, '2026-08-24T19:40:00Z', '{"sentiment": "positive", "emotion": "impressed", "issue": "None / Praise for proactive support", "urgency": "low", "priority": "P3"}'::jsonb, 'Thank you Lucas! Proactive care during bad weather is a standard we strive for. We appreciate your understanding and five-star support!', 'sent'),
('f1a40006-0000-4000-8000-000000000039', 'google', 'Grace Hopper-Lee', 'As a vegan, finding a good plant-based smash burger is tough. The Beyond Smash from BurgerHub was juicy, seasoned wonderfully, and dairy-free cheese was melted to perfection.', 5, '2026-08-23T12:50:00Z', '{"sentiment": "positive", "emotion": "thrilled", "issue": "None / Praise for vegan options", "urgency": "low", "priority": "P3"}'::jsonb, 'Hi Grace, we love hearing this! We put massive effort into making our plant-based burgers every bit as craveable and indulgent. Thank you for the glowing review!', 'approved'),
('f1a40007-0000-4000-8000-000000000040', 'yelp', 'Mason Cooper', 'Consistently delicious. Ordered 15+ times over the past 3 months and quality never dips. Double Cheddar Smash is unbeatable.', 5, '2026-08-22T17:15:00Z', '{"sentiment": "positive", "emotion": "loyal", "issue": "None / Praise for consistency", "urgency": "low", "priority": "P3"}'::jsonb, 'Mason, thank you for being such a loyal BurgerHub fan! 15+ orders and counting—we’re honored to keep serving you five-star burgers every time.', 'sent'),
('f1a40008-0000-4000-8000-000000000041', 'google', 'Isabella Rossi', 'The salted caramel milkshake arrived thick and chilled. Driver arrived in under 20 mins. Will definitely order again.', 5, '2026-08-21T15:30:00Z', '{"sentiment": "positive", "emotion": "happy", "issue": "None / Praise", "urgency": "low", "priority": "P3"}'::jsonb, 'Thank you Isabella! Our insulated cold-packs keep our shakes thick and frosty all the way to your door. Looking forward to your next order!', 'approved'),
('f1a40009-0000-4000-8000-000000000042', 'trustpilot', 'Ethan Huntley', 'Great portion sizes for the price. The Triple Hub stack was huge and fed two of us easily with loaded fries.', 4, '2026-08-19T20:05:00Z', '{"sentiment": "positive", "emotion": "satisfied", "issue": "None / Praise for portion size", "urgency": "low", "priority": "P3"}'::jsonb, 'Hi Ethan, big appetite satisfaction is what we do best! Thanks for sharing the love on our Triple Hub stack.', 'approved'),
('f1a40010-0000-4000-8000-000000000043', 'google', 'Ava Sinclair', 'Love the eco-friendly compostable packaging and rapid contactless delivery. Clean, delicious, guilt-free.', 5, '2026-08-18T13:40:00Z', '{"sentiment": "positive", "emotion": "pleased", "issue": "None / Praise for sustainability", "urgency": "low", "priority": "P3"}'::jsonb, 'Hi Ava, our commitment to sustainability is something we deeply care about. Thank you for noticing and appreciating our 100% compostable boxes!', 'sent'),
('f1a40011-0000-4000-8000-000000000044', 'yelp', 'Noah Sterling', 'Best late night delivery in town. Open till 3 AM and the quality at 2 AM was just as good as prime dinner time.', 5, '2026-08-16T02:30:00Z', '{"sentiment": "positive", "emotion": "enthusiastic", "issue": "None / Praise for late night service", "urgency": "low", "priority": "P3"}'::jsonb, 'Thanks Noah! Late night cravings deserve first-class burgers. Our late shift kitchen crew will love hearing this!', 'approved'),
('f1a40012-0000-4000-8000-000000000045', 'google', 'Mia Thorne', 'The spicy jalapeño ranch smash is unbeatable. Perfectly spicy with tangy house pickles. Fast delivery too.', 5, '2026-08-14T19:00:00Z', '{"sentiment": "positive", "emotion": "delighted", "issue": "None / Praise", "urgency": "low", "priority": "P3"}'::jsonb, 'Hi Mia, our house pickles and jalapeño ranch combo is a fan-favorite! So glad you enjoyed every bite.', 'sent'),

-- --- 5 APP / TECHNICAL ISSUES ---
('f1a50001-0000-4000-8000-000000000046', 'google', 'Benjamin Cole', 'App crashes continuously every time I try to hit the "Place Order" button with Apple Pay on iOS 17. Lost my cart twice.', 2, '2026-08-28T18:45:00Z', '{"sentiment": "negative", "emotion": "frustrated", "issue": "iOS Apple Pay checkout crash bug", "urgency": "high", "priority": "P1"}'::jsonb, 'Hi Benjamin, thank you for alerting us to this iOS Apple Pay bug. Our mobile engineering team just pushed an urgent hotfix (v2.4.2). We’ve credited $15 to your profile for the frustration.', 'approved'),
('f1a50002-0000-4000-8000-000000000047', 'trustpilot', 'Victoria Vance', 'Live GPS courier tracking map was completely stuck showing the driver at the restaurant for 45 minutes, then suddenly he knocked on the door. No delivery notifications received.', 2, '2026-08-26T21:00:00Z', '{"sentiment": "negative", "emotion": "confused", "issue": "Real-time GPS websocket disconnect & missing push alerts", "urgency": "medium", "priority": "P2"}'::jsonb, 'Hi Victoria, we apologize for the lack of tracking updates. We experienced a temporary websocket sync delay on our location servers which has now been restored.', 'pending'),
('f1a50003-0000-4000-8000-000000000048', 'google', 'Tyler Reed', 'The BurgerHub app keeps logging me out every 5 minutes and the SMS OTP verification code takes 10+ minutes to arrive, by which time it expires.', 1, '2026-08-24T15:10:00Z', '{"sentiment": "negative", "emotion": "annoyed", "issue": "Authentication session timeout & slow OTP SMS gateway", "urgency": "high", "priority": "P1"}'::jsonb, 'Hi Tyler, we are truly sorry for the frustrating login loop. We have switched SMS gateway providers for instant OTP delivery and extended authentication token longevity.', 'approved'),
('f1a50004-0000-4000-8000-000000000049', 'yelp', 'Zoe Zimmerman', 'Search and allergen filters on the web app don’t work properly. Checking "Nut Allergy" still showed peanut butter shake in the recommended add-ons.', 2, '2026-08-21T19:30:00Z', '{"sentiment": "negative", "emotion": "concerned", "issue": "Allergen filter glitch in web app recommendation engine", "urgency": "high", "priority": "P1"}'::jsonb, 'Dear Zoe, this allergen filter defect was escalated immediately to our principal web architect and patched within hours. Safety accuracy across all digital menus is paramount.', 'sent'),
('f1a50005-0000-4000-8000-000000000050', 'trustpilot', 'Henry Wallace', 'Re-order button in order history duplicated my previous items 4 times in the cart without warning, causing checkout errors.', 2, '2026-08-18T16:15:00Z', '{"sentiment": "negative", "emotion": "irritated", "issue": "Cart item duplication bug on 1-click reorder", "urgency": "medium", "priority": "P2"}'::jsonb, 'Hi Henry, thanks for reporting this 1-click reorder glitch. Our latest app patch resolved this state mutation bug. We appreciate your patience and help in improving BurgerHub.', 'approved');
